Refactor Build-NeoFreeBird workflow inputs and steps
Updated workflow to use ipa_url input and added IPA validation step.

diff --git a/.github/workflows/Build-NeoFreeBird.yml b/.github/workflows/Build-NeoFreeBird.yml
--- a/.github/workflows/Build-NeoFreeBird.yml
+++ b/.github/workflows/Build-NeoFreeBird.yml
@@ -3,15 +3,18 @@ name: Build Neo
 on:
   workflow_dispatch:
     inputs:
-      decrypted_ipa_url:
-        description: "IPA URL"
+      ipa_url:
+        description: "URL to the IPA"
+        default: ""
         required: true
         type: string
+        
       sdk_version:
         description: "Theos SDK Version"
         default: "16.5"
         required: true
         type: string
+        
       target_version:
         description: "Target iOS Version"
         default: "14.0"
@@ -34,6 +37,31 @@ jobs:
         uses: levibostian/action-hide-sensitive-inputs@v1
         with:
           exclude_inputs: sdk_version,target_version
+          
+      - name: Download and Validate IPA
+        id: ipa
+        run: |
+          IPA_URL="${{ inputs.ipa_url }}"
+
+          # Extract filename from URL
+          FILE_NAME=$(basename "${IPA_URL%%\?*}")
+          NAME_NO_EXT="${FILE_NAME%.*}"
+          echo "IPA file name: $FILE_NAME"
+          
+          wget "$IPA_URL" --no-verbose -O "$NAME_NO_EXT".ipa
+          file_type=$(file --mime-type -b "$NAME_NO_EXT".ipa)
+
+          if [[ "$file_type" != "application/x-ios-app" && "$file_type" != "application/zip" ]]; then
+            echo "::error::Validation failed: The downloaded file is not a valid IPA. Detected type: $file_type."
+          exit 1
+          fi
+          
+          # Expected format: com.atebits.Tweetie2_##.##.ipa
+          # Extract version number
+          X_VERSION=$(echo "$NAME_NO_EXT" | grep -oE '[0-9]+(\.[0-9]+)+')
+          echo "Twitter version detected: $X_VERSION"
+          # Expose it to later steps
+          echo "x_version=$X_VERSION" >> "$GITHUB_OUTPUT"
           
       - name: Install Dependencies
         run: brew install make dpkg ldid
@@ -73,18 +101,6 @@ jobs:
           
       - name: Install Cyan
         run: pipx install --force https://github.com/asdfzxcvbn/pyzule-rw/archive/main.zip
-
-      - name: Prepare iPA
-        id: ipa
-        run: |
-          wget "$IPA_URL" --no-verbose -O main/packages/com.atebits.Tweetie2.ipa
-          unzip -q main/packages/com.atebits.Tweetie2.ipa -d main/tmp
-          X_VERSION=$(grep -A 1 '<key>CFBundleShortVersionString</key>' main/tmp/Payload/Twitter.app/Info.plist |
-            grep '<string>' | awk -F'[><]' '{print $3}')
-          echo "X_VERSION=${X_VERSION}" >> "$GITHUB_ENV"
-          echo "$X_VERSION"
-        env:
-          IPA_URL: ${{ inputs.decrypted_ipa_url }}
 
       - name: Build tweak with Theos
         run: |
